apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app2
  name: app2
spec:
  ports:
  - name: "app2-3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: app2
status:
  loadBalancer: {}
